### ISSUE TITLE
Fail to activate extension for contributing

### ISSUE THREAD

**Issue by ketozhang** [microsoft/vscode-pylint#185]
The [current contributing guide ](https://github.com/microsoft/vscode-pylint/wiki/Contributing-Guide/f13181b4e9359e6d82afad1b7c05e4e1c4b15bec) on the wiki seems to be outdated (seems to be after #128).

I am currently unable to activate the extension in development mode on the main branch (2fae19e66aaf079c3dc190b81f913695ac65b078).

## Steps to reproduce
1. Follow the contributing guide
2. On VSCode, under "Run and Debug", run the task "Debug Extension and Python"

    ```
    ERROR in ./src/extension.ts
    Module build failed (from ./node_modules/vscode-nls-dev/lib/webpack-loader.js):
    TypeError: host.fileExists is not a function
        at Object.fileExists (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:167586:63)
        at Object.host.fileExists (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:117448:47)
        at tryFileLookup (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44293:28)
        at tryFile (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44285:20)
        at tryExtension (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44277:24)
        at tryAddingExtensions (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44255:32)
        at loadModuleFromFile (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44188:45)
        at nodeLoadModuleByRelativeName (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44112:36)
        at tryResolve (/home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44069:34)
        at /home/keto/Projects/vscode-pylint/node_modules/typescript/lib/typescript.js:44032:69
    ```

3. Downgrade typescript to `typescript@"<4.8"`
4. Repeat (2)

    ```
    Activating extension 'ms-python.pylint' failed: Cannot read properties of undefined (reading 'logLevel').
    ```

**Comment by karthiknadig** [comment]
@ketozhang I updated the wiki.

Note that there is a issue with `vscode-nls-dev` and `typescript` version `4.8,*` (ref: https://github.com/microsoft/vscode-nls-dev/issues/42). I have a PR to roll back TS version until this is addressed: https://github.com/microsoft/vscode-pylint/pull/186

But, starting from clean build with typescript pinned to 4.7.4, I did not run into this error. I was able to run and debug the extension.

> Activating extension 'ms-python.pylint' failed: Cannot read properties of undefined (reading 'logLevel').

![image](https://user-images.githubusercontent.com/3840081/188535019-9a3462a0-0a39-4692-930f-e929e0912862.png)


Can you try again after deleting `node_modules` and pinning `typescript` to `4.7.4`?

**Comment by karthiknadig** [comment]
This should be working now.
