### ISSUE TITLE
Server fails for Python <= 3.6

### ISSUE THREAD

**Issue by willmmiles** [microsoft/vscode-pylint#31]
Unfortunately the bundled pydantic attempts to import dataclasses, and thus fails for any environment using a Python interpreter at 3.6 or older.  I think this extension should automatically fall back to using the locally installed pylint such cases.

Debug output from 'Output' tab:
```
Linter Name: Pylint
Linter Module: pylint
Traceback (most recent call last):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\linter\linter_server.py", line 17, in <module>
    from pygls import lsp, server
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\__init__.py", line 2, in <module>
    from pygls.lsp.types.basic_structures import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in <module>
    class JsonRpcMessage(Model):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\main.py", line 304, in __new__
    config=config,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 420, in infer
    field_info=field_info,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 456, in prepare
    self.populate_validators()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\validators.py", line 674, in find_validators
    if is_builtin_dataclass(type_):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\dataclasses.py", line 79, in is_builtin_dataclass
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
[Info  - 11:11:10 a.m.] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\linter\linter_server.py", line 17, in <module>
    from pygls import lsp, server
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\__init__.py", line 2, in <module>
    from pygls.lsp.types.basic_structures import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in <module>
    class JsonRpcMessage(Model):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\main.py", line 304, in __new__
    config=config,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 420, in infer
    field_info=field_info,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 456, in prepare
    self.populate_validators()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\validators.py", line 674, in find_validators
    if is_builtin_dataclass(type_):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\dataclasses.py", line 79, in is_builtin_dataclass
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
[Info  - 11:11:11 a.m.] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\linter\linter_server.py", line 17, in <module>
    from pygls import lsp, server
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\__init__.py", line 2, in <module>
    from pygls.lsp.types.basic_structures import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in <module>
    class JsonRpcMessage(Model):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\main.py", line 304, in __new__
    config=config,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 420, in infer
    field_info=field_info,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 456, in prepare
    self.populate_validators()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\validators.py", line 674, in find_validators
    if is_builtin_dataclass(type_):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\dataclasses.py", line 79, in is_builtin_dataclass
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
[Info  - 11:11:11 a.m.] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\linter\linter_server.py", line 17, in <module>
    from pygls import lsp, server
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\__init__.py", line 2, in <module>
    from pygls.lsp.types.basic_structures import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in <module>
    class JsonRpcMessage(Model):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\main.py", line 304, in __new__
    config=config,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 420, in infer
    field_info=field_info,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 456, in prepare
    self.populate_validators()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\validators.py", line 674, in find_validators
    if is_builtin_dataclass(type_):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\dataclasses.py", line 79, in is_builtin_dataclass
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
[Info  - 11:11:11 a.m.] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\linter\linter_server.py", line 17, in <module>
    from pygls import lsp, server
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\__init__.py", line 23, in <module>
    from pygls.lsp.types import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\__init__.py", line 2, in <module>
    from pygls.lsp.types.basic_structures import *
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pygls\lsp\types\basic_structures.py", line 58, in <module>
    class JsonRpcMessage(Model):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\main.py", line 304, in __new__
    config=config,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 420, in infer
    field_info=field_info,
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 456, in prepare
    self.populate_validators()
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\fields.py", line 670, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\validators.py", line 674, in find_validators
    if is_builtin_dataclass(type_):
  File "c:\Users\wmiles\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pydantic\dataclasses.py", line 79, in is_builtin_dataclass
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
[Error - 11:11:12 a.m.] Connection to server got closed. Server will not be restarted.
```

**Comment by karthiknadig** [comment]
@willmmiles The minimum supported python version is 3.7. I will be updating the readme to mention that.

**Comment by willmmiles** [comment]
Thanks.  I'll look in to how to version lock vscode extensions, and go back to a working version of vscode-python.
