### ISSUE TITLE
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>

### ISSUE THREAD

**Issue by jace** [microsoft/vscode-pylint#333]
Pylint extension v2023.4.0 and prerelease version v2023.5.10901018 are failing for me with this error:

```pytb
Traceback (most recent call last):
  File "/Users/jace/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/tool/lsp_server.py", line 243, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/Users/jace/.vscode/extensions/ms-python.pylint-2023.4.0/bundled/libs/pygls/feature_manager.py", line 174, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>
```
```pytb
Traceback (most recent call last):
  File "/Users/jace/.vscode/extensions/ms-python.pylint-2023.5.10901018/bundled/tool/lsp_server.py", line 257, in <module>
    def code_action(params: lsp.CodeActionParams) -> List[lsp.CodeAction]:
  File "/Users/jace/.vscode/extensions/ms-python.pylint-2023.5.10901018/bundled/libs/pygls/feature_manager.py", line 174, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type <class 'lsprotocol.types.CodeActionOptions'>
```

I'm in a Python 3.9 venv. I can confirm I do not have a conflicting installation of `pygls`.

**Comment by jace** [comment]
The extension was configured to use pylint from the environment. The venv has pylint==2.17.4. Switching to bundled pylint has stopped the crashes.

**Comment by karthiknadig** [comment]
@jace can you share what you have in your environment? run `python -m pip list` and share the output. I am not able to repro this locally.

**Comment by jace** [comment]
Here's the list:

```
Package                       Version      Editable project location
----------------------------- ------------ ----------------------------------------------------------------
aiohttp                       3.8.4
aiohttp-retry                 2.8.3
aiosignal                     1.3.1
alabaster                     0.7.12
alembic                       1.11.0.dev0
aniso8601                     9.0.1
anyio                         3.6.1
appdirs                       1.4.4
appnope                       0.1.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asgiref                       3.5.2
astroid                       2.15.4
async-generator               1.10
async-timeout                 4.0.2
asyncio                       3.4.3
attrs                         23.1.0
Babel                         2.12.1
backcall                      0.2.0
bandit                        1.7.5
base58                        2.1.1
baseframe                     0.4.0.dev0   /Users/jace/Projects/Hasgeek/funnel/build/dependencies/baseframe
baseframe-private-assets      0.1          /Users/jace/Projects/Hasgeek/baseframe-private-assets
bcrypt                        4.0.1
beautifulsoup4                4.12.2
better-profanity              0.6.1
black                         23.3.0
bleach                        6.0.0
blinker                       1.6.2
boto3                         1.26.60
botocore                      1.29.60
Brotli                        1.0.9
build                         0.10.0
cachelib                      0.9.0
cachetools                    5.3.0
cattrs                        22.1.0
certifi                       2023.5.7
cffi                          1.15.1
cfgv                          3.3.1
chardet                       4.0.0
charset-normalizer            3.1.0
chevron                       0.14.0
click                         8.1.3
coaster                       0.7.0        /Users/jace/Projects/Hasgeek/funnel/build/dependencies/coaster
colorama                      0.4.6
commonmark                    0.9.1
coverage                      6.5.0
coveralls                     3.3.1
croniter                      1.3.8
crontab                       1.0.1
cryptography                  40.0.2
cssbeautifier                 1.14.7
cssmin                        0.2.0
cssselect                     1.2.0
cssutils                      2.6.0
curlylint                     0.13.1
dataclasses-json              0.5.7
decorator                     4.4.2
defusedxml                    0.7.1
Deprecated                    1.2.13
diff-match-patch              20200713
dill                          0.3.6
distlib                       0.3.6
djlint                        1.19.16
dnspython                     2.3.0
doc8                          0.11.1
docopt                        0.6.2
docstring-to-markdown         0.11
docutils                      0.16
ecdsa                         0.17.0
EditorConfig                  0.12.3
email-validator               1.1.3
emoji                         2.2.0
exceptiongroup                1.1.1
Fabric3                       1.14.post1
filelock                      3.12.0
flake8                        6.0.0
flake8-assertive              2.1.0
flake8-blind-except           0.2.1
flake8-bugbear                23.3.23
flake8-builtins               2.1.0
flake8-comprehensions         3.12.0
flake8-docstrings             1.7.0
flake8-isort                  6.0.0
flake8-logging-format         0.9.0
flake8-mutable                1.2.0
flake8-plugin-utils           1.3.2
flake8-polyfill               1.0.2
flake8-print                  5.0.0
flake8-pytest-style           1.7.2
Flask                         2.2.5
Flask-Admin                   1.6.0
Flask-Assets                  2.0
flask-babel                   3.1.0
Flask-Caching                 2.0.2
Flask-DebugToolbar            0.13.1
Flask-Executor                1.0.0
Flask-FlatPages               0.8.1
Flask-Lastuser                0.4.1.dev0   /Users/jace/Projects/Hasgeek/flask-lastuser
Flask-Mail                    0.9.1
flask-mailman                 0.3.0
Flask-Migrate                 4.0.4
flask-redis                   0.4.0
Flask-RQ2                     18.3
Flask-SQLAlchemy              3.0.3
Flask-Uploads                 0.2.1
Flask-WTF                     1.1.1
freezegun                     1.2.2
frozenlist                    1.3.3
furl                          2.1.3
future                        0.18.3
geoip2                        4.6.0
gherkin-official              24.0.0
gitdb                         4.0.10
GitPython                     3.1.31
glob2                         0.7
google-api-core               2.8.2
google-api-python-client      2.52.0
google-auth                   2.9.0
google-auth-httplib2          0.1.0
googleapis-common-protos      1.56.3
grapheme                      0.6.0
greenlet                      2.0.2
h11                           0.14.0
html-tag-names                0.1.2
html-void-elements            0.1.0
html2text                     2020.1.16
html5lib                      1.1
html5print                    0.1.2
httplib2                      0.22.0
icalendar                     5.0.5
icdiff                        2.0.5
identify                      2.5.24
idna                          3.4
imagesize                     1.3.0
importlib-metadata            6.6.0
infinity                      1.5
iniconfig                     2.0.0
intervals                     0.9.2
ipython                       7.25.0
ipython-genutils              0.2.0
isort                         5.12.0
isoweek                       1.3.3
itsdangerous                  2.0.1
jedi                          0.18.0
Jinja2                        3.1.2
jmespath                      1.0.1
joblib                        1.2.0
jsbeautifier                  1.14.7
jsmin                         3.0.1
langid                        1.1.6
lazy-object-proxy             1.9.0
line-profiler                 3.3.0
linkify-it-py                 2.0.2
lxml                          4.9.2
lxml-stubs                    0.4.0
Mako                          1.2.4
Markdown                      3.4.3
markdown-it-py                2.2.0
MarkupSafe                    2.1.2
marshmallow                   3.19.0
marshmallow-enum              1.5.1
matplotlib-inline             0.1.2
maxminddb                     2.2.0
mccabe                        0.7.0
mdit-py-plugins               0.3.5
mdurl                         0.1.2
mkdocs-material-extensions    1.1.1
mock                          4.0.3
multidict                     6.0.4
mxsniff                       0.3.5
mypy                          1.2.0
mypy-extensions               1.0.0
ndg-httpsclient               0.5.1
networkx                      2.5.1
nltk                          3.8.1
nodeenv                       1.7.0
numpy                         1.21.2
oauth2                        1.9.0.post1
oauth2client                  4.1.3
oauthlib                      3.2.2
orderedmultidict              1.0.1
outcome                       1.2.0
packaging                     23.1
paramiko                      2.12.0
parse                         1.19.0
parse-type                    0.6.0
parso                         0.8.2
parsy                         1.1.0
passlib                       1.7.4
pathspec                      0.11.1
pbr                           5.11.1
pep517                        0.13.0
pep8-naming                   0.13.3
pexpect                       4.8.0
phonenumbers                  8.13.11
pickleshare                   0.7.5
Pillow                        9.1.1
pip                           23.1.2
pip-compile-multi             2.6.3
pip-tools                     6.13.0
pipdeptree                    2.6.0
pkgconfig                     1.5.5
platformdirs                  3.5.0
pluggy                        1.0.0
ply                           3.4
po2json                       0.2.2
pp-ez                         0.2.0
pprintpp                      0.4.0
pre-commit                    3.3.1
premailer                     3.10.0
progressbar2                  4.2.0
prompt-toolkit                3.0.19
protobuf                      4.21.2
psutil                        5.9.1
psycopg2                      2.9.5
psycopg2-binary               2.9.6
ptpython                      3.0.18
ptyprocess                    0.7.0
py                            1.11.0
pyannotate                    1.2.0
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycodestyle                   2.10.0
pycountry                     22.3.5
pycparser                     2.21
pydantic                      1.8.2
pydocstyle                    6.3.0
PyExecJS                      1.5.1
pyflakes                      3.0.1
Pygments                      2.15.1
pyIsEmail                     2.0.1
PyJWT                         2.6.0
pylint                        2.17.4
pymdown-extensions            9.11
pymongo                       3.11.4
PyNaCl                        1.5.0
pyOpenSSL                     23.1.1
pyparsing                     3.0.9
pypng                         0.20220715.0
pyproject_hooks               1.0.0
PySocks                       1.7.1
pystache                      0.6.0
pytest                        7.3.1
pytest-annotate               1.0.5
pytest-base-url               2.0.0
pytest-bdd                    6.1.1
pytest-cov                    4.0.0
pytest-datadir                1.3.1
pytest-dotenv                 0.5.2
pytest-env                    0.8.1
pytest-html                   3.2.0
pytest-icdiff                 0.6
pytest-metadata               2.0.4
pytest-mock                   3.8.2
pytest-remotedata             0.4.0
pytest-rerunfailures          11.1.2
pytest-selenium               4.0.0
pytest-variables              2.0.0
python-dateutil               2.8.2
python-dotenv                 0.21.1
python-editor                 1.0.4
python-jsonrpc-server         0.3.4
python-magic                  0.4.24
python-utils                  3.5.2
pytoolconfig                  1.2.4
pytz                          2023.3
pyupgrade                     3.4.0
PyVimeo                       1.1.0
pyvips                        2.1.15
PyYAML                        6.0
qrcode                        7.4.2
redis                         4.5.5
Redis-Sentinel-Url            1.0.1
reformat-gherkin              3.0.1
regex                         2022.10.31
requests                      2.30.0
requests-file                 1.5.1
requests-mock                 1.10.0
requests-oauthlib             1.3.1
restructuredtext-lint         1.4.0
rfc3986                       1.5.0
rich                          13.3.5
rope                          1.6.0
rq                            1.14.1
rq-dashboard                  0.6.0
rq-scheduler                  0.13.1
rsa                           4.9
rstcheck                      3.3.1
ruff                          0.0.265
s3transfer                    0.6.0
sadisplay                     0.4.9
secure-cookie                 0.2.0
selenium                      4.9.1
semantic-version              2.10.0
sentry-sdk                    1.22.2
setuptools                    58.5.3
short-url                     1.2.2
simplejson                    3.17.6
six                           1.16.0
slimit                        0.8.1
smmap                         5.0.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
speaklater                    1.3
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    2.0.12
sqlalchemy-json               0.5.0
SQLAlchemy-Utils              0.41.1
statsd                        4.0.1
stevedore                     5.0.0
stringcase                    1.2.0
sttable                       0.0.1
tenacity                      8.2.2
testfixtures                  6.18.5
tinycss2                      1.1.1
tinydb                        4.7.1
tldextract                    3.4.1
tokenize-rt                   5.0.0
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.8
toposort                      1.10
tqdm                          4.65.0
traitlets                     5.0.5
trio                          0.22.0
trio-websocket                0.10.2
tuspy                         1.0.0
tweepy                        4.14.0
twilio                        8.2.0
typeguard                     3.0.2
types-bleach                  4.1.1
types-certifi                 2021.10.8.3
types-click                   7.1.8
types-cryptography            3.3.23.2
types-docutils                0.19.1.6
types-enum34                  1.1.8
types-Flask                   1.1.6
types-geoip2                  3.0.0
types-ipaddress               1.0.8
types-itsdangerous            1.1.6
types-Jinja2                  2.11.9
types-Markdown                3.3.6
types-MarkupSafe              1.1.10
types-maxminddb               1.5.0
types-pyOpenSSL               23.1.0.2
types-python-dateutil         2.8.19.12
types-pytz                    2023.3.0.0
types-PyYAML                  6.0.0
types-redis                   4.5.5.0
types-requests                2.30.0.0
types-setuptools              67.7.0.1
types-simplejson              3.17.6
types-six                     1.16.21.8
types-toml                    0.10.8.6
types-urllib3                 1.26.25.12
types-Werkzeug                1.0.9
typing_extensions             4.5.0
typing-inspect                0.8.0
ua-parser                     0.16.1
uc-micro-py                   1.0.2
UgliPyJS                      0.2.5
ujson                         5.7.0
Unidecode                     1.3.6
unittest2pytest               0.4
uritemplate                   4.1.1
url-normalize                 1.4.3
urllib3                       1.26.15
user-agents                   2.2.0
validators                    0.18.2
virtualenv                    20.23.0
watchdog                      3.0.0
wcwidth                       0.2.6
webassets                     2.0
webencodings                  0.5.1
Werkzeug                      2.2.3
wheel                         0.40.0
whitenoise                    6.4.0
wrapt                         1.15.0
wsproto                       1.2.0
WTForms                       3.0.1
WTForms-JSON                  0.4.0
WTForms-SQLAlchemy            0.3
yarl                          1.9.2
z-base-32                     0.1.2
zipp                          3.15.0
zxcvbn                        4.4.28
```

**Comment by karthiknadig** [comment]
This is really strange; we are using the right type there:
https://github.com/microsoft/vscode-pylint/blob/bd6327068e90468e89277c13114091f77d89e6a6/bundled/tool/lsp_server.py#L253-L256

/cc @alcarney @tombh Any idea what might be going on here?

**Comment by alcarney** [comment]
I think the version of `typeguard` in the venv is upsetting things.

pygls [uses typeguard](https://github.com/openlawlibrary/pygls/blob/3fc13c4bc6eb7438e5b7e8f662d2274cf5f056c6/pygls/lsp/__init__.py#L123) when checking the options type (though I'm not entirely sure why/if that's strictly necessary at this point) and vscode-pylint is [bundling](https://github.com/microsoft/vscode-pylint/blob/main/requirements.txt#L137) typeguard 2.x while the venv above has typeguard 3.x installed.

There was [a commit](https://github.com/openlawlibrary/pygls/commit/9da56dee960e8b9dd35b61d162000eedda492ee5) recently upgrading pygls to typeguard 3.x but it doesn't look like its been released yet.
