### ISSUE TITLE
No such message id or symbol 'c-extension-no-member'

### ISSUE THREAD

**Issue by jstyrud** [microsoft/vscode-pylint#375]
Trying to use the pylint extension in vs code (latest version on both) but I just get the error below. No custom settings.

2023-08-11 18:00:30.387 [info] [Trace - 6:00:30 PM] Received notification 'window/logMessage'.
2023-08-11 18:00:30.388 [info] [Error - 6:00:30 PM] Linting failed with error:
Traceback (most recent call last):
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 109, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True, extra_args=extra_args)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 712, in _run_tool_on_document
    result = utils.run_module(
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_utils.py", line 176, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_utils.py", line 161, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "/home/jonathan/miniconda3/envs/maple/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/jonathan/miniconda3/envs/maple/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/lint/run.py", line 162, in __init__
    linter.enable("c-extension-no-member")
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/lint/message_state_handler.py", line 224, in enable
    self._set_msg_status(
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/lint/message_state_handler.py", line 148, in _set_msg_status
    message_definitions = self._get_messages_to_set(msgid, enable, ignore_unknown)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/lint/message_state_handler.py", line 131, in _get_messages_to_set
    message_definitions = self.linter.msgs_store.get_message_definitions(msgid)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/message/message_definition_store.py", line 74, in get_message_definitions
    for m in self.message_id_store.get_active_msgids(msgid_or_symbol)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/libs/pylint/message/message_id_store.py", line 159, in get_active_msgids
    raise UnknownMessageError(error_msg)
pylint.exceptions.UnknownMessageError: No such message id or symbol 'c-extension-no-member'.

**Comment by karthiknadig** [comment]
@jstyrud This seems like an error with `pylint` itself. Can you share the code that you ran this on? also, does it work if you run it from the command line.

**Comment by jstyrud** [comment]
It's the same print for all files. Here one example:
file.py:
foo = 0
print("hello world")


If I do pylint file.py in the command line I get this print below, so it works there. So it's not pylint itself most likely.
************* Module file
file.py:2:0: C0304: Final newline missing (missing-final-newline)
file.py:1:0: C0114: Missing module docstring (missing-module-docstring)
file.py:1:0: C0104: Disallowed name "foo" (disallowed-name)

-----------------------------------
Your code has been rated at 0.00/10

**Comment by karthiknadig** [comment]
@jstyrud Can you share details of your environment? which python, python version, run `python -m pip list` etc in your environment.

A workaround is to use `"pylint.path":["<path to pylint>"]`.

**Comment by jstyrud** [comment]
Made a new minimal env with the following, get same error as before: "pylint.exceptions.UnknownMessageError: No such message id or symbol 'c-extension-no-member'."

~/proj$ python -m pip list
Package           Version
----------------- -------
astroid           2.15.6
dill              0.3.7
isort             5.12.0
lazy-object-proxy 1.9.0
pip               20.2.2
platformdirs      3.10.0
setuptools        68.0.0
tomli             2.0.1
tomlkit           0.12.1
typing-extensions 4.7.1
wheel             0.38.4
wrapt             1.15.0

~/proj$ python --version
Python 3.8.17


VS code version info:
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by karthiknadig** [comment]
@jstyrud Sorry for the delayed response. It seems like `pylint` is not seeing the python environment were it has the right packages. Do this from a WSL terminal outside of VS Code.
```
> cd <your project>
> conda activate -n <environment>
> code .
```

**Comment by jstyrud** [comment]
> @jstyrud Sorry for the delayed response. It seems like `pylint` is not seeing the python environment where it has the right packages. Do this from a WSL terminal outside of VS Code.
> 
> ```
> > cd <your project>
> > conda activate -n <environment>
> > code .
> ```

Tried that, no difference

**Comment by karthiknadig** [comment]
@DanielNoord Any idea what this can be?

**Comment by Pierre-Sassoulas** [comment]
I think only a really old version of pylint without  'c-extension-no-member' can raise this message. In the pip list I see ``astroid 2.15.6`` but not the pylint version.. (for reference this message was added before 2.6, so ages ago). Try upgrading pylint explicitly (``conda update pylint``) ?

**Comment by DanielNoord** [comment]
This seems related to what is described in this old issue: https://github.com/pylint-dev/pylint/issues/2931. I guess whatever is on `conda-forge` is not actually a new version?

**Comment by Pierre-Sassoulas** [comment]
I'm not sure, ``c-extension-no-member`` is still declared in latest pylint versions so even if we did not delete it properly (we did not delete it either), it should be available in the message store and not crash:

https://github.com/pylint-dev/pylint/blob/df0800ec22c108cb1db244b5c8c4b25db79c58ba/pylint/checkers/typecheck.py#L230-L238

It seems like ``c-extension-no-member`` was added in pylint 1.8.0, six years ago https://github.com/pylint-dev/pylint/commit/b07a1e3fe2f01eca5ac0c4f49a3295e83e5ded22. Definitely upgrade if you use pylint < 1.8.0. Even if you're using python 2.7, you should be able to get 1.9.4.

**Comment by DanielNoord** [comment]
I was referring to the last comments on that issue. This does not seem like a `pylint` issue but rather `conda-forge` obscuring what version is actually being used in which environment.

**Comment by jstyrud** [comment]
I think the reason why pylint didn't show up in the pip list is because I use the one installed with the extension in vscode. If I install pylint explicitly with pip it shows in the pip list but the error message is the same.

More interesting maybe is that I updated VS code (not the conda env) and now I get a different error message:

```
2023-10-19 15:00:05.345 [info] [Error - 3:00:05 PM] Linting failed with error:
Traceback (most recent call last):
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/tool/lsp_server.py", line 144, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True, extra_args=extra_args)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/tool/lsp_server.py", line 773, in _run_tool_on_document
    result = utils.run_module(
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/tool/lsp_utils.py", line 207, in run_module
    return _run_module(module, argv, use_stdin, source)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/tool/lsp_utils.py", line 192, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "/home/jonathan/miniconda3/envs/proj/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/jonathan/miniconda3/envs/proj/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/libs/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/libs/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/libs/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
  File "/home/jonathan/.vscode-server/extensions/ms-python.pylint-2023.9.12921008/bundled/libs/pylint/config/config_initialization.py", line 114, in _config_initialization
    for exc_name in linter.config.overgeneral_exceptions:
AttributeError: 'Namespace' object has no attribute 'overgeneral_exceptions'
```

**Comment by jstyrud** [comment]
Ok, so now I tried pointing to the pip installed version of pylint with pylint.path as suggested and that made it work! 

Would still be nice if it just worked directly with the extension as its supposed to, but this is enough for me.

**Comment by pannaf** [comment]
> Ok, so now I tried pointing to the pip installed version of pylint with pylint.path as suggested and that made it work!
> 
> Would still be nice if it just worked directly with the extension as its supposed to, but this is enough for me.

I had the same issue with this `AttributeError: 'Namespace' object has no attribute 'overgeneral_exceptions'` showing in my OUTPUT panel and the fix for me was also to put `"pylint.path":["<path to pylint, e.g., as /fullpath/here/virtualenvs/venv_name_here/bin/pylint>"]` in my `settings.json` as recommended above.
