### ISSUE TITLE
Bundled lsp_server.py initialization failed

### ISSUE THREAD

**Issue by molasses11** [microsoft/vscode-pylint#386]
At startup, the extension fails with several error notifications, all about not being able to connect to the server. Upon inspecting the extension's output (in the Output pane), it appears that the bundled server in the `lsp_server.py` file fails with an import error, attempting to import `AttrsInstance` from `attr`.

The output looks like:
```bash
2023-09-07 12:50:10.412 [info] Name: Pylint
2023-09-07 12:50:10.412 [info] Module: pylint
2023-09-07 12:50:10.412 [info] Python extension loading
2023-09-07 12:50:10.412 [info] Waiting for interpreter from python extension.
2023-09-07 12:50:10.412 [info] Python extension loaded
2023-09-07 12:50:10.412 [info] Using cwd from `python.analysis.extraPaths`.
2023-09-07 12:50:10.412 [info] Using cwd from `python.analysis.extraPaths`.
2023-09-07 12:50:10.412 [info] Server run command: /home/justin/workspaces/bus_sim/venv/bin/python /home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py
2023-09-07 12:50:10.412 [info] Server: Start requested.
2023-09-07 12:50:11.010 [info] Traceback (most recent call last):
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from lsprotocol import types as lsp
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

2023-09-07 12:50:11.032 [info] [Error - 12:50:11 PM] Server initialization failed.
2023-09-07 12:50:11.032 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.032 [info] [Info  - 12:50:11 PM] Connection to server got closed. Server will restart.
2023-09-07 12:50:11.032 [info] true
2023-09-07 12:50:11.033 [info] [Error - 12:50:11 PM] Pylint client: couldn't create connection to server.
2023-09-07 12:50:11.034 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.427 [info] Traceback (most recent call last):
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from lsprotocol import types as lsp
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

2023-09-07 12:50:11.485 [info] [Error - 12:50:11 PM] Server initialization failed.
2023-09-07 12:50:11.485 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.485 [info] [Info  - 12:50:11 PM] Connection to server got closed. Server will restart.
2023-09-07 12:50:11.485 [info] true
2023-09-07 12:50:11.486 [info] [Error - 12:50:11 PM] Pylint client: couldn't create connection to server.
2023-09-07 12:50:11.486 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.854 [info] Traceback (most recent call last):
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from lsprotocol import types as lsp
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

2023-09-07 12:50:11.887 [info] [Error - 12:50:11 PM] Server initialization failed.
2023-09-07 12:50:11.887 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.887 [info] [Info  - 12:50:11 PM] Connection to server got closed. Server will restart.
2023-09-07 12:50:11.887 [info] true
2023-09-07 12:50:11.888 [info] [Error - 12:50:11 PM] Pylint client: couldn't create connection to server.
2023-09-07 12:50:11.888 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:11.888 [info] [Error - 12:50:11 PM] Restarting server failed
2023-09-07 12:50:11.888 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.284 [info] Traceback (most recent call last):
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from lsprotocol import types as lsp
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

2023-09-07 12:50:12.285 [info] [Error - 12:50:12 PM] Server initialization failed.
2023-09-07 12:50:12.285 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.285 [info] [Info  - 12:50:12 PM] Connection to server got closed. Server will restart.
2023-09-07 12:50:12.285 [info] true
2023-09-07 12:50:12.285 [info] [Error - 12:50:12 PM] Pylint client: couldn't create connection to server.
2023-09-07 12:50:12.286 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.286 [info] [Error - 12:50:12 PM] Restarting server failed
2023-09-07 12:50:12.286 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.749 [info] Traceback (most recent call last):
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py", line 40, in <module>
    from lsprotocol import types as lsp
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/lsprotocol/types.py", line 14, in <module>
    import attrs
  File "/home/justin/.vscode/extensions/ms-python.pylint-2023.6.0/bundled/libs/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/usr/lib/python3/dist-packages/attr/__init__.py)

2023-09-07 12:50:12.751 [info] [Error - 12:50:12 PM] Server initialization failed.
2023-09-07 12:50:12.751 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.751 [info] [Error - 12:50:12 PM] The Pylint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-09-07 12:50:12.752 [info] [Error - 12:50:12 PM] Pylint client: couldn't create connection to server.
2023-09-07 12:50:12.752 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-09-07 12:50:12.752 [info] [Error - 12:50:12 PM] Restarting server failed
2023-09-07 12:50:12.752 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by karthiknadig** [comment]
@molasses11 This means you have unsupported version of `attrs` in your environment. You have few options:
Option 1: Use `"pylint.importStrategy": "useBundled"`. This will use packages that are bundled with the extension. This includes pylint.

Option 2: If you have to use the packages from your environment then please update to attrs==23.1.0

Option 3: If you can't update packages, you can get the extension to use the pylint from environment without loading the packages from the environment. For this you need to set. Use `"pylint.importStrategy": "useBundled"`. But, then set `"pylint.path": ["<path-to-pylint>"]` (in your case it would be `"pylint.path":["/usr/lib/python3", "-m", "pylint"]`

**Comment by molasses11** [comment]
Option 2 worked for me! Thank you for the timely response!
