### ISSUE TITLE
Update documentation clarifying `fromEnvironment `

### ISSUE THREAD

**Issue by oloryn** [microsoft/vscode-pylint#406]
I've just updated a PC I'm developing a particular project on to Python 3.12.  I did a pip freeze to save my requirements, deleted the .venv directory.  I  created a new .venv using Python 3.12, activated it, and did a 'pip install -r requirements.txt'.  When I fired up VSCode to this workspace, I find that I'm getting a message of 

`c:\Users\olory\Projects\set_contest\src\set_contest\set_contest.py:` Fatal error while checking 'c:\Users\olory\Projects\set_contest\src\set_contest\set_contest.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\olory\AppData\Local\pylint\pylint\Cache\pylint-crash-2023-10-04-01-57-47.txt'.

in the Problems tab.   This does not, however appear to be merely a pylint error, as if I run pylint manually against this source from an activated command line, pylint runs fine.  I've restarted VSCode, uninstalled and reinstalled the Pylint extension, and I get the same result.

The referenced template is attached:
[pylint-crash-2023-10-04-01-57-47.txt](https://github.com/microsoft/vscode-pylint/files/12800005/pylint-crash-2023-10-04-01-57-47.txt)

This the dump of the Pylint output window:

2023-10-04 01:57:26.171 [info] Name: Pylint
2023-10-04 01:57:26.171 [info] Module: pylint
2023-10-04 01:57:26.171 [info] Python extension loading
2023-10-04 01:57:26.171 [info] Waiting for interpreter from python extension.
2023-10-04 01:57:26.171 [info] Python extension loaded
2023-10-04 01:57:26.171 [info] Server run command: c:\Users\olory\Projects\set_contest\.venv\Scripts\python.exe c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\tool\lsp_server.py
2023-10-04 01:57:26.171 [info] Server: Start requested.
2023-10-04 01:57:31.286 [info] CWD Server: c:\Users\olory\Projects\set_contest
2023-10-04 01:57:31.286 [info] Settings used to run Server:
[
    {
        "cwd": "c:\\Users\\olory\\Projects\\set_contest",
        "workspace": "file:///c%3A/Users/olory/Projects/set_contest",
        "args": [],
        "severity": {
            "convention": "Information",
            "error": "Error",
            "fatal": "Error",
            "refactor": "Hint",
            "warning": "Warning",
            "info": "Information"
        },
        "path": [],
        "interpreter": [
            "c:\\Users\\olory\\Projects\\set_contest\\.venv\\Scripts\\python.exe"
        ],
        "importStrategy": "useBundled",
        "showNotifications": "off",
        "extraPaths": []
    }
]

2023-10-04 01:57:31.286 [info] Global settings:
{
    "cwd": "C:\\Program Files\\Microsoft VS Code",
    "workspace": "C:\\Program Files\\Microsoft VS Code",
    "args": [],
    "severity": {
        "convention": "Information",
        "error": "Error",
        "fatal": "Error",
        "refactor": "Hint",
        "warning": "Warning",
        "info": "Information"
    },
    "path": [],
    "interpreter": [],
    "importStrategy": "useBundled",
    "showNotifications": "off",
    "extraPaths": []
}

2023-10-04 01:57:31.286 [info] sys.path used to run Server:
   c:\Users\olory\Projects\set_contest
   c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs
   c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\tool
   C:\Users\olory\AppData\Local\Programs\Python\Python312\python312.zip
   C:\Users\olory\AppData\Local\Programs\Python\Python312\DLLs
   C:\Users\olory\AppData\Local\Programs\Python\Python312\Lib
   C:\Users\olory\AppData\Local\Programs\Python\Python312
   c:\Users\olory\Projects\set_contest\.venv
   c:\Users\olory\Projects\set_contest\.venv\Lib\site-packages
2023-10-04 01:57:31.361 [info] c:\Users\olory\Projects\set_contest\.venv\Scripts\python.exe -m pylint --version
2023-10-04 01:57:31.361 [info] CWD Linter: c:\Users\olory\Projects\set_contest
2023-10-04 01:57:44.830 [info] 
pylint 2.17.4
astroid 2.15.5
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

2023-10-04 01:57:44.830 [info] Version info for linter running for C:\Users\olory\Projects\set_contest:
pylint 2.17.4
astroid 2.15.5
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]

2023-10-04 01:57:44.831 [info] SUPPORTED pylint>=2.12.2
FOUND pylint==2.17.4

2023-10-04 01:57:44.847 [info] [Trace - 1:57:44 AM] Sending request 'textDocument/codeAction - (1)'.
2023-10-04 01:57:44.929 [info] [Trace - 1:57:44 AM] Received notification 'window/logMessage'.
2023-10-04 01:57:44.929 [info] c:\Users\olory\Projects\set_contest\.venv\Scripts\python.exe -m pylint --reports=n --output-format=json --clear-cache-post-run=y --from-stdin c:\Users\olory\Projects\set_contest\src\set_contest\set_contest.py
2023-10-04 01:57:44.929 [info] [Trace - 1:57:44 AM] Received notification 'window/logMessage'.
2023-10-04 01:57:44.929 [info] CWD Linter: c:\Users\olory\Projects\set_contest
2023-10-04 01:57:47.673 [info] [Trace - 1:57:47 AM] Received notification 'window/logMessage'.
2023-10-04 01:57:47.673 [info] Exception on node <ImportFrom l.10 at 0x25ce4400440> in file 'c:\Users\olory\Projects\set_contest\src\set_contest\set_contest.py'
Traceback (most recent call last):
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\pylint\checkers\imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\nodes\_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\astroid\rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\pylint\checkers\imports.py", line 549, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\olory\.vscode\extensions\ms-python.pylint-2023.6.0\bundled\libs\pylint\checkers\imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

2023-10-04 01:57:47.674 [info] [Trace - 1:57:47 AM] Received notification 'window/logMessage'.
2023-10-04 01:57:47.674 [info] file:///c%3A/Users/olory/Projects/set_contest/src/set_contest/set_contest.py :
[
    {
        "type": "fatal",
        "module": "set_contest.set_contest",
        "obj": "",
        "line": 1,
        "column": 0,
        "endLine": null,
        "endColumn": null,
        "path": "src\\set_contest\\set_contest.py",
        "symbol": "astroid-error",
        "message": "c:\\Users\\olory\\Projects\\set_contest\\src\\set_contest\\set_contest.py: Fatal error while checking 'c:\\Users\\olory\\Projects\\set_contest\\src\\set_contest\\set_contest.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\\Users\\olory\\AppData\\Local\\pylint\\pylint\\Cache\\pylint-crash-2023-10-04-01-57-47.txt'.",
        "message-id": "F0002"
    }
]

**Comment by karthiknadig** [comment]
The bundled pylint does not support 3.12. You can either set the “pylint.importStrategy” to ‘fromEnvironment’ or set “pylint.path” to point to the pylint binary in your env,

**Comment by oloryn** [comment]
OK, setting pylint.importStrategy to fromEnvironment worked.

I'll note that the note appearing at the top of the extension Detail tab: "The bundled pylint is only used if there is no installed version of pylint found in the selected python environment." seems to imply that fromEnvironment is effectively the default.  Is it possible that that was the default (possibly before pylint.importStrategy was a setting?) and the note at the top wasn't updated when that changed?

Is it likely that before long the bundled pylint will be updated to something 3.12-compatible?

**Comment by karthiknadig** [comment]
The text needs to be updated.
