### ISSUE TITLE
Pylint couldn't connect to server using "fromEnvironment" import strategy

### ISSUE THREAD

**Issue by pizzacrystal** [microsoft/vscode-pylint#442]
## Issue briefing
once "pylint.importStrategy" is set to "fromEnvironment", pylint failed to start every time when openning a python project folder, and the notification from pylint extension is as follow:
> Server initialization failed.
Message: Pending response rejected since connection got disposed
The Pylint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
Pylint client: couldn't create connection to server.
Message: Pending response rejected since connection got disposed
Restarting server failed
Message: Pending response rejected since connection got disposed

**however**, if "pylint.importStrategy" was set to "useBundled", everything goes well.

## Versions
Pylint extension version: `v2023.10.0`
python version: `3.10.10`
pylint(env) version: `3.0.2`
VSC version: 1.84.0 (system setup)
OS: Windows_NT x64 10.0.19045

## Configs
pylint.importStrategy: `fromEnvironment`
pylint.path: (empty)

## Outputs
<details>
<summary>pylint outputs</summary>
2023-11-06 11:25:26.451 [info] Name: Pylint

2023-11-06 11:25:26.451 [info] Module: pylint

2023-11-06 11:25:26.451 [info] Python extension loading

2023-11-06 11:25:26.451 [info] Waiting for interpreter from Python extension.

2023-11-06 11:25:26.451 [info] No interpreter found from setting pylint.interpreter

2023-11-06 11:25:26.451 [info] Getting interpreter from ms-python.python extension for workspace d:\Temp\python\ExtractCSV

2023-11-06 11:25:26.451 [info] Python extension loaded

2023-11-06 11:25:26.451 [info] Interpreter from ms-python.python extension for d:\Temp\python\ExtractCSV: c:\Program Files\Python310\python.exe

2023-11-06 11:25:26.451 [info] No interpreter found from setting pylint.interpreter

2023-11-06 11:25:26.451 [info] Getting interpreter from ms-python.python extension for workspace d:\Temp\python\ExtractCSV

2023-11-06 11:25:26.451 [info] Interpreter from ms-python.python extension for d:\Temp\python\ExtractCSV: c:\Program Files\Python310\python.exe

2023-11-06 11:25:26.451 [info] Server run command: c:\Program Files\Python310\python.exe c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py

2023-11-06 11:25:26.451 [info] Server: Start requested.

2023-11-06 11:25:27.079 [info] Traceback (most recent call last):

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py", line 66, in <module>

  from pygls import server, uris, workspace

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\server.py", line 37, in <module>

  from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\lsp\__init__.py", line 38, in <module>

  from typeguard import check_type

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\__init__.py", line 21, in <module>

  from ._importhook import ImportHookManager as ImportHookManager

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\_importhook.py", line 22, in <module>

  from typing_extensions import Buffer

ImportError: cannot import name 'Buffer' from 'typing_extensions' (c:\Program Files\Python310\lib\site-packages\typing_extensions.py)

2023-11-06 11:25:27.275 [info] [**Error** - 11:25:27] Server initialization failed.

2023-11-06 11:25:27.275 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:27.275 [info] [Info  - 11:25:27] Connection to server got closed. Server will restart.

2023-11-06 11:25:27.275 [info] true

2023-11-06 11:25:27.275 [info] [**Error** - 11:25:27] Pylint client: couldn't create connection to server.

2023-11-06 11:25:27.275 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:28.495 [info] Traceback (most recent call last):

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py", line 66, in <module>

  from pygls import server, uris, workspace

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\server.py", line 37, in <module>

  from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\lsp\__init__.py", line 38, in <module>

  from typeguard import check_type

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\__init__.py", line 21, in <module>

  from ._importhook import ImportHookManager as ImportHookManager

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\_importhook.py", line 22, in <module>

  from typing_extensions import Buffer

ImportError: cannot import name 'Buffer' from 'typing_extensions' (c:\Program Files\Python310\lib\site-packages\typing_extensions.py)

2023-11-06 11:25:28.504 [info] [**Error** - 11:25:28] Server initialization failed.

2023-11-06 11:25:28.504 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:28.504 [info] [Info  - 11:25:28] Connection to server got closed. Server will restart.

2023-11-06 11:25:28.504 [info] true

2023-11-06 11:25:28.504 [info] [**Error** - 11:25:28] Pylint client: couldn't create connection to server.

2023-11-06 11:25:28.504 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:28.505 **[error]** Server: Start failed: **Error**: Pending response rejected since connection got disposed

2023-11-06 11:25:29.261 [info] Traceback (most recent call last):

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py", line 66, in <module>

  from pygls import server, uris, workspace

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\server.py", line 37, in <module>

  from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\lsp\__init__.py", line 38, in <module>

  from typeguard import check_type

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\__init__.py", line 21, in <module>

  from ._importhook import ImportHookManager as ImportHookManager

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\_importhook.py", line 22, in <module>

  from typing_extensions import Buffer

ImportError: cannot import name 'Buffer' from 'typing_extensions' (c:\Program Files\Python310\lib\site-packages\typing_extensions.py)

2023-11-06 11:25:29.386 [info] [**Error** - 11:25:29] Server initialization failed.

2023-11-06 11:25:29.386 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:29.386 [info] [Info  - 11:25:29] Connection to server got closed. Server will restart.

2023-11-06 11:25:29.386 [info] true

2023-11-06 11:25:29.386 [info] [**Error** - 11:25:29] Pylint client: couldn't create connection to server.

2023-11-06 11:25:29.386 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:29.387 [info] [**Error** - 11:25:29] Restarting server failed

2023-11-06 11:25:29.387 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:30.438 [info] Traceback (most recent call last):

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py", line 66, in <module>

  from pygls import server, uris, workspace

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\server.py", line 37, in <module>

  from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\lsp\__init__.py", line 38, in <module>

  from typeguard import check_type

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\__init__.py", line 21, in <module>

  from ._importhook import ImportHookManager as ImportHookManager

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\_importhook.py", line 22, in <module>

  from typing_extensions import Buffer

ImportError: cannot import name 'Buffer' from 'typing_extensions' (c:\Program Files\Python310\lib\site-packages\typing_extensions.py)

2023-11-06 11:25:30.516 [info] [**Error** - 11:25:30] Server initialization failed.

2023-11-06 11:25:30.516 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:30.516 [info] [Info  - 11:25:30] Connection to server got closed. Server will restart.

2023-11-06 11:25:30.516 [info] true

2023-11-06 11:25:30.516 [info] [**Error** - 11:25:30] Pylint client: couldn't create connection to server.

2023-11-06 11:25:30.516 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:30.516 [info] [**Error** - 11:25:30] Restarting server failed

2023-11-06 11:25:30.516 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:31.142 [info] Traceback (most recent call last):

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\tool\lsp_server.py", line 66, in <module>

  from pygls import server, uris, workspace

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\server.py", line 37, in <module>

  from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\pygls\lsp\__init__.py", line 38, in <module>

  from typeguard import check_type

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\__init__.py", line 21, in <module>

  from ._importhook import ImportHookManager as ImportHookManager

 File "c:\Users\pizza\.vscode\extensions\ms-python.pylint-2023.10.0\bundled\libs\typeguard\_importhook.py", line 22, in <module>

  from typing_extensions import Buffer

ImportError: cannot import name 'Buffer' from 'typing_extensions' (c:\Program Files\Python310\lib\site-packages\typing_extensions.py)

2023-11-06 11:25:31.182 [info] [**Error** - 11:25:31] Server initialization failed.

2023-11-06 11:25:31.182 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:31.182 [info] [**Error** - 11:25:31] The Pylint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

2023-11-06 11:25:31.182 [info] [**Error** - 11:25:31] Pylint client: couldn't create connection to server.

2023-11-06 11:25:31.182 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 

2023-11-06 11:25:31.182 [info] [**Error** - 11:25:31] Restarting server failed

2023-11-06 11:25:31.182 [info]  Message: Pending response rejected since connection got disposed

 Code: -32097 
</details>

**Comment by karthiknadig** [comment]
That often means that you have some package in the environment that is not compatible. Try updating packages that might impact the server here are the server requirements: https://github.com/microsoft/vscode-pylint/blob/main/requirements.txt

If you are not able to update packages you can still use environment `pylint` using the `pylint.path` even with `useBundled` setting. Just set it to `"pylint.path": ["${interpreter}", "-m", "pylint"]`

**Comment by pizzacrystal** [comment]
> That often means that you have some package in the environment that is not compatible. Try updating packages that might impact the server here are the server requirements: https://github.com/microsoft/vscode-pylint/blob/main/requirements.txt
> 
> If you are not able to update packages you can still use environment `pylint` using the `pylint.path` even with `useBundled` setting. Just set it to `"pylint.path": ["${interpreter}", "-m", "pylint"]`

exactly, solved after re-installing with requirements list.
Thank you so much!
