### ISSUE TITLE
cannot import name 'find_pylintrc' from 'pylint.config'

### ISSUE THREAD

**Issue by danielWagnerr** [microsoft/vscode-pylint#444]
I'm trying to use this extension but I'm stuck with this error:

```shell

2023-11-06 14:03:44.476 [info] [Error - 2:03:44 PM] Linting failed with error:
Traceback (most recent call last):
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 144, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True, extra_args=extra_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 770, in _run_tool_on_document
    result = utils.run_module(
             ^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_utils.py", line 207, in run_module
    return _run_module(module, argv, use_stdin, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_utils.py", line 192, in _run_module
    runpy.run_module(module, run_name="__main__")
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pylint/config/config_initialization.py", line 57, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
ImportError: cannot import name 'find_pylintrc' from 'pylint.config' (/Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pylint/config/__init__.py)
```

I just installed it and ran into this issue

The other logs before the errors are:

```shell

2023-11-06 14:14:11.953 [info] sys.path used to run Server:
   /Users/daniel/Workspace/visa/scripts-visa
   /Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs
   /Users/daniel/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool
   /Users/daniel/.pyenv/versions/3.11.3/lib/python311.zip
   /Users/daniel/.pyenv/versions/3.11.3/lib/python3.11
   /Users/daniel/.pyenv/versions/3.11.3/lib/python3.11/lib-dynload
   /Users/daniel/Workspace/visa/scripts-visa/venv/lib/python3.11/site-packages
2023-11-06 14:14:11.954 [info] /Users/daniel/Workspace/visa/scripts-visa/venv/bin/python -m pylint --version
2023-11-06 14:14:11.954 [info] CWD Linter: /Users/daniel/Workspace/visa/scripts-visa
2023-11-06 14:14:11.973 [info] 
pylint 3.0.2
astroid 3.0.1
Python 3.11.3 (main, May 18 2023, 11:53:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]


2023-11-06 14:14:11.973 [info] Version info for linter running for /Users/daniel/Workspace/visa/scripts-visa:
pylint 3.0.2
astroid 3.0.1
Python 3.11.3 (main, May 18 2023, 11:53:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]

2023-11-06 14:14:11.974 [info] SUPPORTED pylint>=2.12.2
FOUND pylint==3.0.2
```

**Comment by karthiknadig** [comment]
@DanielNoord Do you know what this might be?

@danielWagnerr You can set `pylint.importStrategy` to `fromEnvironment` and have it use the pylint from your environment as a workaround.

**Comment by DanielNoord** [comment]
Yes, this means that the configuration is not compatible with `pylint` `3.0` and higher. 

See https://github.com/pylint-dev/pylint/issues/9105 for a pointer on how to solve this issue. You'll need to update your configuration.

**Comment by danielWagnerr** [comment]
Thank you guys, changing the config file worked!
