### ISSUE TITLE
Pylint fails to start with `ImportError: cannot import name 'Buffer' from 'typing_extensions' `

### ISSUE THREAD

**Issue by mRcSchwering** [microsoft/vscode-pylint#446]
*How to I find out the version details of my installed pylint extension?

Hi, since today in one python3.10 project the pylint extension in VSCode fails starting. The output shows this:

```
2023-11-07 16:39:19.958 [info] Name: Pylint
2023-11-07 16:39:19.958 [info] Module: pylint
2023-11-07 16:39:19.958 [info] Python extension loading
2023-11-07 16:39:19.958 [info] Waiting for interpreter from Python extension.
2023-11-07 16:39:19.958 [info] No interpreter found from setting pylint.interpreter
2023-11-07 16:39:19.958 [info] Getting interpreter from ms-python.python extension for workspace /home/marc/magic-soup
2023-11-07 16:39:19.958 [info] Python extension loaded
2023-11-07 16:39:19.958 [info] Interpreter from ms-python.python extension for /home/marc/magic-soup: /home/marc/anaconda3/envs/magicsoup_dev/bin/python
2023-11-07 16:39:19.958 [info] No interpreter found from setting pylint.interpreter
2023-11-07 16:39:19.958 [info] Getting interpreter from ms-python.python extension for workspace /home/marc/magic-soup
2023-11-07 16:39:19.958 [info] Interpreter from ms-python.python extension for /home/marc/magic-soup: /home/marc/anaconda3/envs/magicsoup_dev/bin/python
2023-11-07 16:39:19.958 [info] Server run command: /home/marc/anaconda3/envs/magicsoup_dev/bin/python /home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py
2023-11-07 16:39:19.958 [info] Server: Start requested.
2023-11-07 16:39:20.926 [info] Traceback (most recent call last):
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 66, in <module>
    from pygls import server, uris, workspace
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/server.py", line 37, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/marc/anaconda3/envs/magicsoup_dev/lib/python3.10/site-packages/typing_extensions.py)

2023-11-07 16:39:21.068 [info] [Error - 4:39:21 PM] Server initialization failed.
2023-11-07 16:39:21.068 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:21.068 [info] [Info  - 4:39:21 PM] Connection to server got closed. Server will restart.
2023-11-07 16:39:21.068 [info] true
2023-11-07 16:39:21.069 [info] [Error - 4:39:21 PM] Pylint client: couldn't create connection to server.
2023-11-07 16:39:21.069 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:21.831 [info] Traceback (most recent call last):
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 66, in <module>
    from pygls import server, uris, workspace
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/server.py", line 37, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/marc/anaconda3/envs/magicsoup_dev/lib/python3.10/site-packages/typing_extensions.py)

2023-11-07 16:39:21.969 [info] [Error - 4:39:21 PM] Server initialization failed.
2023-11-07 16:39:21.969 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:21.969 [info] [Info  - 4:39:21 PM] Connection to server got closed. Server will restart.
2023-11-07 16:39:21.969 [info] true
2023-11-07 16:39:21.969 [info] [Error - 4:39:21 PM] Pylint client: couldn't create connection to server.
2023-11-07 16:39:21.969 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:21.969 [error] Server: Start failed: Error: Pending response rejected since connection got disposed
2023-11-07 16:39:22.731 [info] Traceback (most recent call last):
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 66, in <module>
    from pygls import server, uris, workspace
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/server.py", line 37, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/marc/anaconda3/envs/magicsoup_dev/lib/python3.10/site-packages/typing_extensions.py)

2023-11-07 16:39:22.854 [info] [Error - 4:39:22 PM] Server initialization failed.
2023-11-07 16:39:22.854 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:22.854 [info] [Info  - 4:39:22 PM] Connection to server got closed. Server will restart.
2023-11-07 16:39:22.854 [info] true
2023-11-07 16:39:22.854 [info] [Error - 4:39:22 PM] Pylint client: couldn't create connection to server.
2023-11-07 16:39:22.854 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:22.854 [info] [Error - 4:39:22 PM] Restarting server failed
2023-11-07 16:39:22.854 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.415 [info] Traceback (most recent call last):
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 66, in <module>
    from pygls import server, uris, workspace
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/server.py", line 37, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/marc/anaconda3/envs/magicsoup_dev/lib/python3.10/site-packages/typing_extensions.py)

2023-11-07 16:39:23.481 [info] [Error - 4:39:23 PM] Server initialization failed.
2023-11-07 16:39:23.481 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.481 [info] [Info  - 4:39:23 PM] Connection to server got closed. Server will restart.
2023-11-07 16:39:23.481 [info] true
2023-11-07 16:39:23.481 [info] [Error - 4:39:23 PM] Pylint client: couldn't create connection to server.
2023-11-07 16:39:23.481 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.481 [info] [Error - 4:39:23 PM] Restarting server failed
2023-11-07 16:39:23.481 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.933 [info] Traceback (most recent call last):
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/tool/lsp_server.py", line 66, in <module>
    from pygls import server, uris, workspace
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/server.py", line 37, in <module>
    from pygls.lsp import ConfigCallbackType, ShowDocumentCallbackType
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/pygls/lsp/__init__.py", line 38, in <module>
    from typeguard import check_type
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/__init__.py", line 21, in <module>
    from ._importhook import ImportHookManager as ImportHookManager
  File "/home/marc/.vscode/extensions/ms-python.pylint-2023.10.0/bundled/libs/typeguard/_importhook.py", line 22, in <module>
    from typing_extensions import Buffer
ImportError: cannot import name 'Buffer' from 'typing_extensions' (/home/marc/anaconda3/envs/magicsoup_dev/lib/python3.10/site-packages/typing_extensions.py)

2023-11-07 16:39:23.989 [info] [Error - 4:39:23 PM] Server initialization failed.
2023-11-07 16:39:23.989 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.989 [info] [Error - 4:39:23 PM] The Pylint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-11-07 16:39:23.989 [info] [Error - 4:39:23 PM] Pylint client: couldn't create connection to server.
2023-11-07 16:39:23.989 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-11-07 16:39:23.989 [info] [Error - 4:39:23 PM] Restarting server failed
2023-11-07 16:39:23.989 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by karthiknadig** [comment]
@mRcSchwering for this extension to work there is a minimum requirement on the typing_extension please upgrade it to `typing-extensions==4.8.0`

**Comment by mRcSchwering** [comment]
I still get the same error after upgrading. I guess the VSCode extension is using a different `typing-extensions`. How can I upgrade the one that is used?

**Comment by karthiknadig** [comment]
Can you check the version after upgrading? also, please use `python -m pip` , when you use `pip` directly there is no guarantee where it is installing (like is it installing to global or your virtual environment). I suspect that the `pip` installed the upgrade in the global environment, but the virtual environment version is not upgraded. 

Please read this more info: https://snarky.ca/why-you-should-use-python-m-pip/?web=1

**Comment by mRcSchwering** [comment]
Thx.

For some reason `pip install typing-extensions --upgrade` actually only uninstalled `typing-extensions` (according to STDOUT). `pip install` fixed it.
