### ISSUE TITLE
Crash ``'Module' object has no attribute 'doc_node'`` (as of v2022.1.10911002)

### ISSUE THREAD

**Issue by timeterror** [microsoft/vscode-pylint#77]
When parsing the following file:

```python
"An example that crashes."
# Local modules
import logging

```

pylint crashed with an ``AttributeError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\lint\pylinter.py", line 1111, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\lint\pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\lint\pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\lint\pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\utils\ast_walker.py", line 73, in walk
    callback(astroid)
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\checkers\base\docstring_checker.py", line 109, in visit_module
    self._check_docstring("module", node)
  File "c:\Users\marc.pont\.vscode\extensions\ms-python.pylint-2022.1.10911002\bundled\libs\pylint\checkers\base\docstring_checker.py", line 161, in _check_docstring
    docstring = node.doc_node.value if node.doc_node else None
AttributeError: 'Module' object has no attribute 'doc_node'
```

The extension settings are:
```
"pylint.args": [
        "--max-line-length=100",
        "--disable=C0413,W0105,W0511,W1201,W1202,W1203",
        "--extension-pkg-whitelist=pyodbc,pandas,numpy",
        "--ignored-classes=DatetimeIndex,ExtensionIndex,Index",
        "--good-names=Run,_",
        "--max-args=25",
        "--argument-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--attr-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--class-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--const-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--function-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--method-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--module-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--variable-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}",
        "--inlinevar-rgx=\\b[a-zA-Z_][a-zA-Z0-9_]{0,30}"
    ]
```

**Comment by DanielNoord** [comment]
@karthiknadig The issue was filed here: https://github.com/PyCQA/pylint/issues/6505

However, we can't reproduce with the version that shown by (presumably) `pip list`. Is there an easy way to let @timeterror show which version and environment the extension is using?
